GET http://localhost:3000

###

POST http://localhost:3000/api/v1/auth/signup/REALTOR
Content-Type: application/json

{
  "name": "test",
  "phone": "123",
  "email": "realtor@gmail.com",
  "password": "realtor",
  "productKey": "$2b$10$2oWuU4B8PnGErW4CQ0pPEOMIy0Ec.yOi4ujs7eJvpPPntl6PCa27q"
}
###

POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "ilker@gmail.com",
  "password": "123"
}

###


POST http://localhost:3000/api/v1/auth/key
Content-Type: application/json

{
  "email": "realtor@gmail.com",
  "userType": "REALTOR"
}

###

POST http://localhost:3000/api/v1/auth/key
Content-Type: application/json

{
  "email": "test@test.com",
  "userType": "REALTOR"
}


###

GET  http://localhost:3000/api/v1/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjQ4MzQ0NjU2LCJleHAiOjE2NDg1MTc0NTZ9.jBi830sJHVcQn5NdJ_HA50raYawnsUCBdhoZWmGjkzI


###

GET  http://localhost:3000/api/v1/home/3
###

POST  http://localhost:3000/api/v1/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ4MzQ1ODkxLCJleHAiOjE2NDg1MTg2OTF9.KDTjH5bM-kpGUmAN-liIGuthONftSbQf0he6xJvDoKE
Content-Type: application/json

{
  "address": "REALTORE AIT",
  "numberOfBedrooms": 1,
  "numberOfBathrooms": 2,
  "city": "soemthing",
  "price": 3,
  "landSize": 4,
  "propertyType": "test",
  "images": [{"url": "img1"}, {"url": "img2"}, {"url": "img3"}],
  "propertyType": "CONDO"
}

###

PUT  http://localhost:3000/api/v1/home/12
Content-Type: application/json

{
  "address": "UPDATED",
  "numberOfBedrooms": 111,
  "numberOfBathrooms": 11,
  "city": "UPDATED",
  "price": 111,
  "landSize": 111,
  "propertyType": "CONDO"
}

###

DELETE  http://localhost:3000/api/v1/home/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjQ4MzQ1ODkxLCJleHAiOjE2NDg1MTg2OTF9.KDTjH5bM-kpGUmAN-liIGuthONftSbQf0he6xJvDoKE
